name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SERVICE_NAME: philharlow.github.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.SERVICE_NAME }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ env.SERVICE_NAME }}-

      - name: Install dependencies
        run: |
          npm install --prefer-offline --no-audit

      - name: Webpack build
        run: |
          npm run build

      - name: Copy to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: build